In [1]:
import pandas as pd

In [2]:
h=pd.read_csv("Housing.csv")
h

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [3]:
h.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [4]:
nh=h.select_dtypes("int64")
nh

        price  area  bedrooms  bathrooms  stories  parking
0    13300000  7420         4          2        3        2
1    12250000  8960         4          4        4        3
2    12250000  9960         3          2        2        2
3    12215000  7500         4          2        2        3
4    11410000  7420         4          1        2        2
..        ...   ...       ...        ...      ...      ...
540   1820000  3000         2          1        1        2
541   1767150  2400         3          1        1        0
542   1750000  3620         2          1        1        0
543   1750000  2910         3          1        1        0
544   1750000  3850         3          1        2        0

[545 rows x 6 columns]

In [5]:
x=nh.drop("price",axis="columns")
x

     area  bedrooms  bathrooms  stories  parking
0    7420         4          2        3        2
1    8960         4          4        4        3
2    9960         3          2        2        2
3    7500         4          2        2        3
4    7420         4          1        2        2
..    ...       ...        ...      ...      ...
540  3000         2          1        1        2
541  2400         3          1        1        0
542  3620         2          1        1        0
543  2910         3          1        1        0
544  3850         3          1        2        0

[545 rows x 5 columns]

In [6]:
y=nh["price"]
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [10]:
y_pred=lr.predict(x_test)
y_pred

array([6178627.50326817, 6370140.85865473, 3283148.15702491,
       4226007.94816032, 3409685.55116742, 4262158.3499693 ,
       5493440.53152356, 5559897.74293016, 3373715.42245305,
       3020513.18649699, 9519985.014906  , 3250408.25967962,
       3184310.73107686, 3639160.73159381, 3907874.98339005,
       6174323.64572264, 3148160.32926788, 4872535.73454622,
       4826205.69113307, 3888527.39095668, 5222386.81260559,
       4294589.3803585 , 3162381.17719464, 4193028.43115341,
       5747707.28367816, 7619041.42465271, 2989724.54874165,
       4794005.74968624, 7434038.64867547, 3457027.28535552,
       5102872.70577387, 3982998.90101382, 6215707.38061091,
       4724828.08224185, 4307759.63367012, 5625853.70972471,
       4791990.70630181, 3815116.83871034, 3261429.41224535,
       4879463.83866909, 5326652.37523624, 3156512.70502897,
       6345431.50216771, 4316575.21358847, 4120177.6080224 ,
       4190668.52130486, 6710808.14327266, 4603723.42489655,
       4521704.65093633, 3637248.18329028, 7841708.56409845,
       3299587.35299202, 4772882.73353005, 4071574.4701165 ,
       3957195.63851065, 3085375.2472754 , 6971252.23454901,
       3422953.86233246, 4825111.78511692, 3209020.08756387,
       4878575.94908725, 4526835.83267043, 5037411.34253001,
       3567305.75662553, 5012521.71294839, 4518334.58320817,
       6744881.56629572, 3608274.03598504, 7430586.3657061 ,
       4622435.71535643, 4747675.70627309, 5141167.77110126,
       4967468.91586526, 6953067.98798002, 3201985.39486833,
       5334424.86498618, 4478181.87891677, 3522520.04799283,
       4377434.97188446, 3823567.27232485, 7153467.8960285 ,
       4617172.00915621, 5746394.03784009, 5236916.52748843,
       3206746.99307111, 7231644.4837051 , 3051399.88210576,
       4084924.99652274, 7480866.86948139, 7732906.74287638,
       3572558.22032813, 5010612.23186411, 3718650.56510848,
       3734909.48798097, 8681030.24021201, 3975727.65587591,
       5623198.06375392, 6649034.75205514, 5213203.01916415,
       5562072.7795695 , 4357723.76604259, 5963514.54002297,
       4094108.78996417, 6072397.55021372, 5361443.315474  ,
       5311028.75433724, 7199715.72420045, 6058267.44824741,
       5931714.21149267])

In [11]:
from sklearn.metrics import r2_score,mean_squared_error
r2_score(y_test,y_pred)

0.5464062355495864

In [12]:
lr.intercept_

np.float64(4706527.385321101)

In [13]:
print(lr.coef_)

[680058.42414123 112973.18562909 565408.61793601 424354.81176353
 288348.7726677 ]

In [14]:
x

     area  bedrooms  bathrooms  stories  parking
0    7420         4          2        3        2
1    8960         4          4        4        3
2    9960         3          2        2        2
3    7500         4          2        2        3
4    7420         4          1        2        2
..    ...       ...        ...      ...      ...
540  3000         2          1        1        2
541  2400         3          1        1        0
542  3620         2          1        1        0
543  2910         3          1        1        0
544  3850         3          1        2        0

[545 rows x 5 columns]

In [15]:
from sklearn.linear_model import Lasso,Ridge

In [16]:
lasso = Lasso(alpha=0.1)
lasso.fit(x_train, y_train)

y_pred_lasso = lasso.predict(x_test)

print("\nLasso Regression")
print("MSE:", mean_squared_error(y_test, y_pred_lasso))
print("R2 Score:", r2_score(y_test, y_pred_lasso))

Lasso Regression
MSE: 2292721662778.182
R2 Score: 0.5464062123917687

In [17]:
print(lasso.coef_)

[680058.36417334 112973.14330951 565408.57775827 424354.74893703
 288348.70986412]

In [18]:
ridge = Ridge(alpha=1.0)
ridge.fit(x_train, y_train)

y_pred_ridge = ridge.predict(x_test)

print("\nRidge Regression")
print("MSE:", mean_squared_error(y_test, y_pred_ridge))
print("R2 Score:", r2_score(y_test, y_pred_ridge))

Ridge Regression
MSE: 2293867305607.654
R2 Score: 0.5461795575480068

In [19]:
print(ridge.coef_)

[678673.36548148 113669.70765825 564390.29003319 423523.13470614
 288296.02803672]

In [20]:
lr = LinearRegression()
ridge = Ridge(alpha=10)
lasso = Lasso(alpha=0.1)

lr.fit(x_train, y_train)
ridge.fit(x_train, y_train)
lasso.fit(x_train, y_train)

print("Linear:", lr.coef_)
print("Ridge:", ridge.coef_)
print("Lasso:", lasso.coef_)

Linear: [680058.42414123 112973.18562909 565408.61793601 424354.81176353
 288348.7726677 ]
Ridge: [666511.70061345 119590.63348316 555455.54722932 416256.33592057
 287725.37020698]
Lasso: [680058.36417334 112973.14330951 565408.57775827 424354.74893703
 288348.70986412]